[book]
authors = ["cz"]
language = "zh"
title = "数学建模指南"
description = "完整的数学建模学习指南，涵盖理论基础、方法技巧和实战案例"
src = "src"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = false
copy-js = true
